name: Auto Merge ws-objects -> main

on:
  push:
    branches:
      - desarrollo/feature/ws-objects

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Obtener todas las ramas
        run: git fetch origin

      - name: Cambiar a main
        run: git checkout main

      - name: Intentar merge
        run: |
          git merge origin/desarrollo/feature/ws-objects --no-edit

      - name: Push a main
        run: |
          git push origin main
